version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - pip3 install pyOpenSSL --upgrade
      - echo "Deploying to ${STAGE}"
      - ls -lart
      - . env/.env.$STAGE
  build:
    commands:
      - ls -ltr
      - echo $IMAGE_TAG
      - sam deploy -t infra.yaml --region=${AWS_DEFAULT_REGION} --stack-name $STACK_NAME --no-fail-on-empty-changeset --capabilities=CAPABILITY_NAMED_IAM CAPABILITY_IAM --parameter-overrides "ParameterKey=Environment,ParameterValue=${STAGE}" "ParameterKey=ResourcePrefix,ParameterValue=${PREFIX}" "ParameterKey=Region,ParameterValue=${AWS_DEFAULT_REGION}" "ParameterKey=VpcId,ParameterValue=${VPCID}" "ParameterKey=SubnetIds,ParameterValue=\"${PublicSubnet1},${PublicSubnet2},${PublicSubnet3}\"" "ParameterKey=SecurityGroupIds,ParameterValue=${SecurityGroupID}" "ParameterKey=PipelineArtifactBucket,ParameterValue=${ARTIFACT_BUCKET}" "ParameterKey=MaxvCpus,ParameterValue=${MAX_VCPUS:-40}" "ParameterKey=ContainerVcpus,ParameterValue=${CONTAINER_VCPUS:-0.25}" "ParameterKey=ContainerMemory,ParameterValue=${CONTAINER_MEMORY:-512}" "ParameterKey=ImageTag,ParameterValue=${IMAGE_TAG}"