version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - pip3 install pyOpenSSL --upgrade
      - echo "Deploying to ${STAGE}"
      - ls -lart
      - . env/.env.$STAGE
  build:
    commands:
      - ls -ltr
      - echo $IMAGE_TAG
      - echo $SECRET_ARN
      - echo $VPCID
      - echo $PUBLIC_SUBNET_1 
      - echo $PUBLIC_SUBNET_2
      - echo $PUBLIC_SUBNET_3
      - echo $SECURITYGROUP
      - echo $RDS_HOST
      - sam deploy -t devops/infra.yaml --region=${AWS_DEFAULT_REGION} --s3-bucket $ARTIFACT_BUCKET --stack-name $STACK_NAME --no-fail-on-empty-changeset --capabilities=CAPABILITY_NAMED_IAM CAPABILITY_IAM --parameter-overrides "ParameterKey=Environment,ParameterValue=${STAGE}" "ParameterKey=ResourcePrefix,ParameterValue=${PREFIX}" "ParameterKey=Region,ParameterValue=${AWS_DEFAULT_REGION}" "ParameterKey=VpcId,ParameterValue=${VPCID}" "ParameterKey=SubnetIds,ParameterValue=\"${PUBLIC_SUBNET_1},${PUBLIC_SUBNET_2},${PUBLIC_SUBNET_3}\"" "ParameterKey=SecurityGroupIds,ParameterValue=${SECURITYGROUP}" "ParameterKey=PipelineArtifactBucket,ParameterValue=${ARTIFACT_BUCKET}" "ParameterKey=MaxvCpus,ParameterValue=${MAX_VCPUS:-40}" "ParameterKey=ContainerVcpus,ParameterValue=${CONTAINER_VCPUS:-1}" "ParameterKey=ContainerMemory,ParameterValue=${CONTAINER_MEMORY:-2048}" "ParameterKey=ImageTag,ParameterValue=${IMAGE_TAG}" "ParameterKey=S3BucketName,ParameterValue=${S3_BUCKET_NAME}" "ParameterKey=SecretArn,ParameterValue=${SECRET_ARN}" "ParameterKey=RDSHost,ParameterValue=${RDS_HOST}"